# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "financial-rag-tfstate-637423656824-us-east-1"
    dynamodb_table = "financial-rag-tflock-staging"
    encrypt        = true
    key            = "staging/environments/staging/s3/terraform.tfstate"
    region         = "us-east-1"
  }
}
