apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: financial-rag-gateway
  namespace: financial-rag
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: financial-rag-tls
      hosts:
        - api.financial-rag.cloudfrugal.com
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - api.financial-rag.cloudfrugal.com
